const express = require('express')
const router = express.Router()
const AddProduct = require('../controllers/products/addProduct')
const getAllProducts = require('../controllers/products/getAllProducts')
const getOneProduct = require('../controllers/products/getOneProduct')
const verifyToken = require('../middleware/validUser')
const AddCategory = require('../controllers/products/AddCategory')
const deleteProduct = require('../controllers/products/deleteProduct')
const editProduct = require('../controllers/products/editProduct')
const getAllCategory = require('../controllers/products/getAllCategory')
const upload = require('../services/cloudinary.service')
router.post('/addproduct', verifyToken, upload.array('image', 5), AddProduct)
router.put('/editproduct/:id', verifyToken, upload.array('image', 5), editProduct)
router.get('/getallproducts' , getAllProducts)
router.get('/getoneproduct/:id' , getOneProduct)
router.post('/addcategory' , AddCategory)
router.delete('/deleteproduct/:id' , deleteProduct)
router.get('/getallcategory' , getAllCategory)
module.exports = router